name: Manual run

on: workflow_dispatch

jobs:
    wdio-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install
              working-directory: homework_1/

            - name: Run Tests
              run: npm run test
              working-directory: homework_1/
              env:
                  LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
                  VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
                  INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}